# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_na_cpp__impl <- function(df, indices) {
    .Call('_naniar_count_na_cpp__impl', PACKAGE = 'naniar', df, indices)
}

