# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_row_na_cpp <- function(df, parallel) {
    .Call(`_naniar_count_row_na_cpp`, df, parallel)
}

prop_row_na_cpp <- function(df, parallel) {
    .Call(`_naniar_prop_row_na_cpp`, df, parallel)
}

